### ISSUE TITLE
Play music fully and add Skip option

### ISSUE THREAD

**Issue by knight-ryu12** [ohasanov-hbrw/osus-revented#1]
osu have skip button when music have some time before actual drain time starts.

**Comment by ohasanov-hbrw** [comment]
Added a skip option in the recent builds but its not a clickable button, you just need to press "s" on the keyboard. I am planning to add the UI elements properly in the future.

**Comment by ohasanov-hbrw** [comment]
I think I managed to add a skip function, and I also think that the whole music file is being played. I will consider this issue as fixed for now...
