### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by xugro** [ohasanov-hbrw/osus-revented#4]
Doesn't compile on ubuntu 
![image](https://user-images.githubusercontent.com/82907135/183398314-ef117762-361d-43d3-835e-4f46dabe65da.png)

**Comment by xugro** [comment]
prereqs not complete

**Comment by tixvage** [comment]
probably you need to download some x11 devel packages from your package manager

**Comment by tixvage** [comment]
https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux
check this Page

**Comment by ohasanov-hbrw** [comment]
This issue should be fixed now, since we completely botched the GLFW Windowing System. 

Now you should have SDL2 though
