### ISSUE TITLE
ARM64 devices get stuck at this step on compilation

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [ohasanov-hbrw/osus-revented#7]
Using latest proot-distro, the error is:

g++ -DSUPPORT_FILEFORMAT_PNG -DSUPPORT_FILEFORMAT_BMP -DSUPPORT_FILEFORMAT_JPG -o bin/osus  object/fastrender.o object/followpoint.o object/fs.o object/gamemanager.o object/gui.o object/hitobjectcircle.o object/hitobjectslider.o object/hitobjectspinner.o object/main.o object/parser.o object/SDLutils.o object/state.o object/time_util.o object/utils.o -lstdc++ -Lvendor/raylib/src -lraylib -Lvendor/zip/build -lzip -lpthread -ldl -lSDL2main -lSDL2 -lpthread
/usr/bin/ld: cannot open output file bin/osus: No such file or directory
collect2: error: ld returned 1 exit status                 make: *** [Makefile:28: osus] Error 1
root@localhost:~/osus-revented#

OS: Ubuntu 22.04 64-Bit LTS
Device: Samsung Galaxy A21s (European)
Kernel: 6.2.1 PRoot-distro
CPU: 2.002 GHz
Allocated RAM: 3710MB
Terminal:PRoot
App:Termux, Termux-X11 for GUI
I can comment in turkish if you want to as i am also turkish, i will use virgl with zink to play the game so ot has reasonable performance when i compile it, also anything(like mounting drives, AppImages and other stuff that requires drives to be mounted and dismounted cannot be used in PRoot.)

**Comment by DJMoffinz** [comment]
this happens to me too, seems like this may be the case on more than just arm devices
i am on arch linux x86_64
have tried this with and without sudo prepended and as root
also i cloned the repo directly, i'll try downloading a the release tag and see if that makes a difference

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> this happens to me too, seems like this may be the case on more than just arm devices i am on arch linux x86_64 have tried this with and without sudo prepended and as root also i cloned the repo directly, i'll try downloading a the release tag and see if that makes a difference

Any updates?

**Comment by ohasanov-hbrw** [comment]
Ok sorry for being a bit late, 

> Using latest proot-distro, the error is:
> 
> g++ -DSUPPORT_FILEFORMAT_PNG -DSUPPORT_FILEFORMAT_BMP -DSUPPORT_FILEFORMAT_JPG -o bin/osus object/fastrender.o object/followpoint.o object/fs.o object/gamemanager.o object/gui.o object/hitobjectcircle.o object/hitobjectslider.o object/hitobjectspinner.o object/main.o object/parser.o object/SDLutils.o object/state.o object/time_util.o object/utils.o -lstdc++ -Lvendor/raylib/src -lraylib -Lvendor/zip/build -lzip -lpthread -ldl -lSDL2main -lSDL2 -lpthread /usr/bin/ld: cannot open output file bin/osus: No such file or directory collect2: error: ld returned 1 exit status make: *** [Makefile:28: osus] Error 1 root@localhost:~/osus-revented#
> 
> OS: Ubuntu 22.04 64-Bit LTS Device: Samsung Galaxy A21s (European) Kernel: 6.2.1 PRoot-distro CPU: 2.002 GHz Allocated RAM: 3710MB Terminal:PRoot App:Termux, Termux-X11 for GUI I can comment in turkish if you want to as i am also turkish, i will use virgl with zink to play the game so ot has reasonable performance when i compile it, also anything(like mounting drives, AppImages and other stuff that requires drives to be mounted and dismounted cannot be used in PRoot.)

Are you sure that the directories "object" and "bin" exist? Also all dependencies? I can't really understand much from the output message. Also, the code currently will definitely crash. (I forgot to change the game start directory in "globals.hpp", you will see what I mean) Playing on a phone also probably won't work... I tried compiling the project on a clean install of arch, after installing SDL2 and the compiling dependencies it works, the makefile should be easy enough to understand I also feel like

**Comment by ohasanov-hbrw** [comment]
> this happens to me too, seems like this may be the case on more than just arm devices i am on arch linux x86_64 have tried this with and without sudo prepended and as root also i cloned the repo directly, i'll try downloading a the release tag and see if that makes a difference

That release is a really old build, don't even bother... Just clone the repository, create the folders for the build. ("make deps" should normally do it but IDK) Currently, the game will crash because of the start directory, forgot to change that. I am working on renewing the whole memory management (its leaking now) system (and the 3ds port) so yeah that build would be better to test.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> Ok sorry for being a bit late,
> 
> > Using latest proot-distro, the error is:
> > g++ -DSUPPORT_FILEFORMAT_PNG -DSUPPORT_FILEFORMAT_BMP -DSUPPORT_FILEFORMAT_JPG -o bin/osus object/fastrender.o object/followpoint.o object/fs.o object/gamemanager.o object/gui.o object/hitobjectcircle.o object/hitobjectslider.o object/hitobjectspinner.o object/main.o object/parser.o object/SDLutils.o object/state.o object/time_util.o object/utils.o -lstdc++ -Lvendor/raylib/src -lraylib -Lvendor/zip/build -lzip -lpthread -ldl -lSDL2main -lSDL2 -lpthread /usr/bin/ld: cannot open output file bin/osus: No such file or directory collect2: error: ld returned 1 exit status make: *** [Makefile:28: osus] Error 1 root@localhost:~/osus-revented#
> > OS: Ubuntu 22.04 64-Bit LTS Device: Samsung Galaxy A21s (European) Kernel: 6.2.1 PRoot-distro CPU: 2.002 GHz Allocated RAM: 3710MB Terminal:PRoot App:Termux, Termux-X11 for GUI I can comment in turkish if you want to as i am also turkish, i will use virgl with zink to play the game so ot has reasonable performance when i compile it, also anything(like mounting drives, AppImages and other stuff that requires drives to be mounted and dismounted cannot be used in PRoot.)
> 
> Are you sure that the directories "object" and "bin" exist? Also all dependencies? I can't really understand much from the output message. Also, the code currently will definitely crash. (I forgot to change the game start directory in "globals.hpp", you will see what I mean) Playing on a phone also probably won't work... I tried compiling the project on a clean install of arch, after installing SDL2 and the compiling dependencies it works, the makefile should be easy enough to understand I also feel like
:/
![Screenshot_20240514-195235_Termux](https://github.com/ohasanov-hbrw/osus-revented/assets/144390627/4872c045-a2ba-4536-b107-0854d499c47e)

**Comment by ohasanov-hbrw** [comment]
Yeah this is expected. Change the folder in "globals.hpp". You will see it. Sorry that I am not pushing the fix, I don't want to mess up the repo :/

**Comment by GuythatUhmCreatesRandomStuff** [comment]
Ok just figured out the issue(s) and tinkered with it and it looks good(NATIVE TERMUX STILL DOESNT WORK) except the W.I.P text crashes the game with 3 images not being found
